[tool.black]
target-version = ["py311"]
skip-string-normalization = true
line-length = 120
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|migrations|migrations|venv)/'
